// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuoLike.Server.Data;

#nullable disable

namespace QuoLike.Server.Migrations
{
    [DbContext(typeof(QuoLikeDbContext))]
    partial class QuoLikeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("QuoLike.Server.Models.QuoteSelect", b =>
                {
                    b.Property<string>("QuoteSelectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuoteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("QuoteSelectId");

                    b.ToTable("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
